refactor(API communication::add_resource):wip
crazyfactory/vue-product-description-manager pull request #23
Opened 2017-12-29 04:09 UTC by lalita13008

close #22

2017-12-29 04:25 UTC, Solomonic commented on assets/app.js
> +                _this = this
do we need `_this` ?

2017-12-29 04:29 UTC, Solomonic commented on assets/app.js
> +                    api_endpoint, {
please use proper format
```
fetch(
  api_end_point,
  {
    method: 'POST',
    body: JSON.stringify(....)
  },
)
```

2018-01-02 08:42 UTC, adhocore commented
> refactor(API communication::add_resource):wip

WIP (in caps) should be prefixed and not suffixed :)

2018-01-05 02:10 UTC, Solomonic requested changes

2018-01-05 02:10 UTC, Solomonic commented on assets/app.js
> +                if(this.rawMetatags==null){
remove double `if(this.rawMetatags==null){`

2018-01-05 02:10 UTC, Solomonic commented on assets/app.js
> +                if(this.rawMetatags==null){
remove double `if(this.rawMetatags==null){`

2018-01-05 02:10 UTC, Solomonic commented on assets/app.js
> +                        if (typeof _this.modelCodeSuccess == 'undefined') {
what is `modelCodeSuccess `?
It should be define in `data`

2018-01-15 13:51 UTC, merged